package db

var UsersCollectionName = "users"
var AuthOrganisationsCollectionName = "authOrganisations"
var AuthOrganisationUserPermissionsCollectionName = "authOrganisationUserPermissions"
var AuthGlobalUserPermissionsCollectionName = "authGlobalUserPermissions"
var InstancesCollectionName = "instances"
var InstanceRequestsCollectionName = "instanceRequests"
var InstancesSubscriptionsCollectionName = "instancesSubscriptions"
var StripeLedgerCollectionName = "stripeLedger"
var StripeConfigCollectionName = "stripeConfig"
var StripeProductsCollectionName = "stripeProducts"
var StripeProductPurchasesRecurringCollectionName = "stripeProductPurchasesRecurring"
var UserBalancesCollectionName = "userBalances"
var NginxTemplatesCollectionName = "nginxTemplates"
