package db

var UsersCollectionName = "users"
var OrganisationsCollectionName = "organisations"
var OrganisationUserPermissionsCollectionName = "organisationUserPermissions"
var GlobalUserPermissionsCollectionName = "globalUserPermissions"
var InstancesCollectionName = "instances"
var InstanceRequestsCollectionName = "instanceRequests"
var InstancesSubscriptionsCollectionName = "instancesSubscriptions"
var StripeLedgerCollectionName = "stripeLedger"
var StripeConfigCollectionName = "stripeConfig"
var StripeProductsCollectionName = "stripeProducts"
var StripeProductPricesCollectionName = "stripeProductPrices"
var StripeProductPurchasesRecurringCollectionName = "stripeProductPurchasesRecurring"
var UserBalancesCollectionName = "userBalances"
var NginxTemplatesCollectionName = "nginxTemplates"
