import { StrictMode } from "react";
import { createRoot } from "react-dom/client";
import { BrowserRouter, useRoutes } from "react-router-dom";
import routes from "~react-pages"; // auto-generated by the plugin
import "@repo/pokkit-components/styles.css";
import "@repo/pokkit-auth/styles.css";
import { useReactiveAuthStoreSync } from "@repo/pokkit-auth";
import { pb } from "./config/pocketbaseConfig";

function App() {
  useReactiveAuthStoreSync({ pb });

  return useRoutes(routes);
}

createRoot(document.getElementById("app")!).render(
  <StrictMode>
    <BrowserRouter basename={import.meta.env.VITE_APP_BASE_URL}>
      <App />
    </BrowserRouter>
  </StrictMode>,
);
