import { StrictMode } from "react";
import { createRoot } from "react-dom/client";
import { BrowserRouter, useLocation, useNavigate, useRoutes } from "react-router-dom";
import routes from "~react-pages"; // auto-generated by the plugin
import "@repo/pokkit-components/styles.css";
import "@repo/pokkit-auth/styles.css";
import { SignOutButton, useReactiveAuthStore, useReactiveAuthStoreSync } from "@repo/pokkit-auth";
import { pb } from "./config/pocketbaseConfig";
import {
  Button,
  Header,
  LayoutTemplate,
  LeftSidebar,
  SidebarButton,
} from "@repo/pokkit-components";

const Routes = () => {
  return useRoutes(routes);
};

const App = () => {
  useReactiveAuthStoreSync({ pb });
  const authDataStore = useReactiveAuthStore();

  const location = useLocation();
  const navigate = useNavigate();

  const isAuthenticated = !!authDataStore?.record.id;

  return (
    <LayoutTemplate
      Header={
        <Header
          Left={<div>Pokkit-Whisper</div>}
          Right={
            isAuthenticated ? (
              <SignOutButton pb={pb} />
            ) : (
              <Button onClick={() => navigate("/auth/sign-in")}>Sign In</Button>
            )
          }
        />
      }
      LeftSidebar={
        <LeftSidebar
          top={
            <>
              <SidebarButton href="/" isHighlighted={location.pathname === "/"} iconName="Home">
                Home
              </SidebarButton>
            </>
          }
          middle={
            <>
              <SidebarButton
                href="/page1"
                isHighlighted={location.pathname === "/page1"}
                iconName="Home"
              >
                Page 1
              </SidebarButton>
              <SidebarButton
                href="/page2"
                isHighlighted={location.pathname === "/page2"}
                iconName="Home"
              >
                Page 2
              </SidebarButton>
              <SidebarButton
                href="/page3"
                isHighlighted={location.pathname === "/page3"}
                iconName="Home"
              >
                Page 3 hhhhhhhhhhhhhhhhhhhhhhhhhhh
              </SidebarButton>
            </>
          }
          bottom={
            <>
              {isAuthenticated ? (
                <SidebarButton
                  iconName="LogOut"
                  onClick={() => pb.authStore.clear()}
                  isHighlighted={false}
                >
                  Sign Out
                </SidebarButton>
              ) : (
                <>
                  <SidebarButton
                    iconName="UserPlus"
                    onClick={() => navigate("/auth/sign-up")}
                    isHighlighted={location.pathname.startsWith("/auth/sign-up")}
                  >
                    Sign Up
                  </SidebarButton>
                  <SidebarButton
                    iconName="LogIn"
                    onClick={() => navigate("/auth/sign-in")}
                    isHighlighted={location.pathname.startsWith("/auth/sign-in")}
                  >
                    Sign In
                  </SidebarButton>
                </>
              )}
            </>
          }
        />
      }
    >
      <Routes />
    </LayoutTemplate>
  );
};

createRoot(document.getElementById("app")!).render(
  <StrictMode>
    <BrowserRouter basename={import.meta.env.VITE_APP_BASE_URL}>
      <App />
    </BrowserRouter>
  </StrictMode>,
);
