import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  toolsSidebar: [{ type: "autogenerated", dirName: "." }],
  skillsSidebar: [{ type: "autogenerated", dirName: "." }],
  plansSidebar: [{ type: "autogenerated", dirName: "." }],
};

export default sidebars;
