import { useAuthSync } from "@repo/pokkit-auth";
import { LayoutTemplate, Modal } from "@repo/pokkit-components";
import { Toaster } from "@repo/pokkit-shadcn";
import { StrictMode } from "react";
import { createRoot, Root } from "react-dom/client";
import { BrowserRouter, useRoutes } from "react-router-dom";
import routes from "~react-pages"; // auto-generated by the plugin
import { Header } from "./components/Header";
import { LeftSidebar } from "./components/LeftSidebar";
import { envConfig } from "./config/envConfig";
import { pb } from "./config/pocketbaseConfig";

import "@repo/pokkit-auth/styles.css";
import "@repo/pokkit-components/styles.css";
import "@repo/pokkit-shadcn/styles.css";

const Routes = () => {
  return useRoutes(routes);
};

const App = () => {
  useAuthSync({ pb });

  return (
    <>
      <Toaster />
      <Modal />

      <LayoutTemplate Header={<Header pb={pb} />} LeftSidebar={<LeftSidebar pb={pb} />}>
        <Routes />
      </LayoutTemplate>
    </>
  );
};

const container = document.getElementById("app") as HTMLElement & { _reactRoot?: Root };
const getRoot = () => {
  if (container._reactRoot) return container._reactRoot;

  const root = createRoot(container);
  container._reactRoot = root;
  return root;
};
getRoot().render(
  <StrictMode>
    <BrowserRouter basename={envConfig.VITE_APP_BASE_URL}>
      <App />
    </BrowserRouter>
  </StrictMode>,
);
