import {
  signOut,
  TUser,
  useAuthMethodsListStoreSync,
  useReactiveAuthStore,
  useReactiveAuthStoreSync,
} from "@repo/pokkit-auth";
import "@repo/pokkit-auth/styles.css";
import {
  Button,
  Header,
  LayoutTemplate,
  LeftSidebar,
  SidebarButton,
  ThemeToggle,
} from "@repo/pokkit-components";
import "@repo/pokkit-components/styles.css";
import { Toaster } from "@repo/pokkit-shadcn";
import "@repo/pokkit-shadcn/styles.css";
import { StrictMode } from "react";
import { createRoot, Root } from "react-dom/client";
import { BrowserRouter, useLocation, useNavigate, useRoutes } from "react-router-dom";
import routes from "~react-pages"; // auto-generated by the plugin
import { envConfig } from "./config/envConfig";
import { pb, PocketBase } from "./config/pocketbaseConfig";

import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuLabel,
  DropdownMenuSeparator,
  DropdownMenuTrigger,
} from "@repo/pokkit-shadcn";
import { getInitialsFromString } from "./lib/stringUtils";

const ProfileDropdown = (p: { pb: PocketBase; user: TUser }) => {
  const navigate = useNavigate();

  return (
    <DropdownMenu>
      <DropdownMenuTrigger asChild>
        <button className="h-9 w-9 rounded-full bg-muted text-foreground font-medium text-sm flex items-center justify-center hover:bg-muted/80 transition-colors focus:outline-none focus:ring-2 focus:ring-ring">
          {getInitialsFromString(p.user.name)}
        </button>
      </DropdownMenuTrigger>

      <DropdownMenuContent align="end" className="w-56">
        <DropdownMenuLabel>
          <div className="flex flex-col space-y-1">
            <p className="text-sm font-medium leading-none">{p.user.name}</p>
            <p className="text-xs text-muted-foreground">{p.user.email}</p>
          </div>
        </DropdownMenuLabel>

        <DropdownMenuSeparator />

        <DropdownMenuItem onClick={() => navigate("/auth/email-change-request")}>
          Request Email Change Token
        </DropdownMenuItem>

        <DropdownMenuSeparator />

        <DropdownMenuItem onClick={() => signOut({ pb })} className="text-destructive">
          Sign out
        </DropdownMenuItem>
      </DropdownMenuContent>
    </DropdownMenu>
  );
};

const Routes = () => {
  return useRoutes(routes);
};

const App = () => {
  useReactiveAuthStoreSync({ pb });
  useAuthMethodsListStoreSync({ pb });
  const authDataStore = useReactiveAuthStore();

  const location = useLocation();
  const navigate = useNavigate();

  return (
    <>
      <Toaster />

      <LayoutTemplate
        Header={
          <Header
            Left={<div>{envConfig.VITE_APP_DISPLAY_NAME}</div>}
            Right={
              <span className="flex gap-2">
                <ThemeToggle />
                {authDataStore ? (
                  <ProfileDropdown pb={pb} user={authDataStore.record} />
                ) : (
                  <Button onClick={() => navigate("/auth/sign-in")}>Sign In</Button>
                )}
              </span>
            }
          />
        }
        LeftSidebar={
          <LeftSidebar
            top={
              <>
                <SidebarButton href="/" isHighlighted={location.pathname === "/"} iconName="Home">
                  Home
                </SidebarButton>
              </>
            }
            middle={
              <>
                <SidebarButton
                  href="/page1"
                  isHighlighted={location.pathname === "/page1"}
                  iconName="Home"
                >
                  Page 1
                </SidebarButton>
                <SidebarButton
                  href="/page2"
                  isHighlighted={location.pathname === "/page2"}
                  iconName="Home"
                >
                  Page 2
                </SidebarButton>
                <SidebarButton
                  href="/page3"
                  isHighlighted={location.pathname === "/page3"}
                  iconName="Home"
                >
                  Page 3 hhhhhhhhhhhhhhhhhhhhhhhhhhh
                </SidebarButton>
              </>
            }
            bottom={
              <>
                {authDataStore ? (
                  <SidebarButton
                    iconName="LogOut"
                    onClick={() => pb.authStore.clear()}
                    isHighlighted={false}
                  >
                    Sign Out
                  </SidebarButton>
                ) : (
                  <>
                    <SidebarButton
                      iconName="UserPlus"
                      onClick={() => navigate("/auth/sign-up")}
                      isHighlighted={location.pathname.startsWith("/auth/sign-up")}
                    >
                      Sign Up
                    </SidebarButton>
                    <SidebarButton
                      iconName="LogIn"
                      onClick={() => navigate("/auth/sign-in")}
                      isHighlighted={location.pathname.startsWith("/auth/sign-in")}
                    >
                      Sign In
                    </SidebarButton>
                  </>
                )}
              </>
            }
          />
        }
      >
        <Routes />
      </LayoutTemplate>
    </>
  );
};

const container = document.getElementById("app") as HTMLElement & { _reactRoot?: Root };
const getRoot = () => {
  if (container._reactRoot) return container._reactRoot;

  const root = createRoot(container);
  container._reactRoot = root;
  return root;
};
getRoot().render(
  <StrictMode>
    <BrowserRouter basename={envConfig.VITE_APP_BASE_URL}>
      <App />
    </BrowserRouter>
  </StrictMode>,
);

// createRoot(document.getElementById("app")!).render(
//   <StrictMode>
//     <BrowserRouter basename={envConfig.VITE_APP_BASE_URL}>
//       <App />
//     </BrowserRouter>
//   </StrictMode>,
// );
