name: pokkit-starter-deploy-build-on-merge
on:
  push:
    branches:
      - main
jobs:
  deploy_pokkit_starter_build_on_merge:
    runs-on: ubuntu-latest
    outputs:
      portNumber: ${{ steps.deploy.outputs.portNumber }}
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v3
        with:
          version: 9

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"

      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - run: pnpm i

      - name: Build app-db for linux/amd64
        working-directory: apps/pokkit-starter/pokkit-starter-db
        run: GOOS=linux GOARCH=amd64 go build -o build/app-db ./src/...

      - name: add pb_config
        working-directory: apps/pokkit-starter/pokkit-starter-db
        run: pnpm run copy-pbconfig-to-build

      - name: Deploy build to PocketBase
        id: deploy
        working-directory: apps/pokkit-starter/pokkit-starter-deploy
        run: pnpm run deploy-build

      - name: Echo port number
        run: echo "Port number: ${{ jobs.deploy_pokkit_starter_build_on_merge.outputs.portNumber }}"